repos:

-   repo: https://github.com/hhatto/autopep8
    rev: v2.0.4
    hooks:
    -   id: autopep8
        args: ["--global-config", "package/pyproject.toml"]

-   repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
    -   id: black
        types: [python]
        args: ["--config", "package/pyproject.toml"]

-   repo: https://github.com/pycqa/isort
    rev: 5.11.2
    hooks:
    -   id: isort
        name: isort (python)